<style type="text/css" media="screen, print">
    @page
    {
        size: auto;
        margin: 25px;
    }
</style>
<?php 
$data = $this->data;

$add_rows = 69 - sizeof($this->data);
for ($i = $add_rows; $i > 0; $i--) {
    $data[] = [
        "Department" => " ",
        "First Name" => " ",
        "Last Name" => " ",
        "Signature" => " ",
    ];
}

$row_num = 1;
?>
<div class="jumbotron">
    <h1>Training Sign In Sheet</h1>
    
    <div class="row">
    	<div class="col">
    		Class: <?php echo $data[0]['Class Name']; ?><br>		
    		Instructor: <?php echo $data[0]['Instructor']; ?><br>
    	</div>
    	<div class="col">
    		Date Schedule: <?php echo $data[0]['Date Schedule']; ?>
    	</div>
    </div>
</div>
<div class="row">
	<div class="col">
		<table class="table table-striped table-lg text-nowrap w-auto">
        	<thead>
        		<tr>
        	<?php 
//         	   $header = array_keys($this->data[0]); 
//         	   foreach ($header as $key) {
//         	       if (strpos($key, $this->primary_key) === 0 ) { continue; }
//         	       echo "<th>$key</th>";
//         	   }
           ?>
           			<th>#</th>
           			<th>Department</th>
           			<th>Name</th>
           			<th style="width: 100%;">Signature</th>
        		</tr>
        	</thead>
        	<tbody>
        		<?php foreach ($data as $record) : ?>
        		<tr>
        			<th scope="row"><?=$row_num++;?></th>
        			<td><?php echo $record['Department']?></td>
        			<td><?php echo $record['First Name'] . ' ' . $record['Last Name']?></td>
        			<td></td>
        		</tr>
        		<?php endforeach; ?>
        	</tbody>
        </table>
	</div>
</div>