<a href="<?=$this->url($this->route, ['action'=>'clear'])?>" class="btn btn-danger">Truncate Database Tables</a>
<a href="<?=$this->url($this->route, ['action'=>'create'])?>" class="btn btn-primary">Populate Database Tables</a>

<?php if (!file_exists('./data/files')) { ?>
	<p>
    	Files Directory does not Exist
    	<a href="<?=$this->url($this->route, ['action'=>'createfolders'])?>" class="btn btn-primary">Create Upload Folders</a>
	</p>
<?php } else { ?>
	<p>Files Directory Exists.</p>
<?php } ?>