<div class="row">
	<div class="col-md">    
        <div class="card mb-4">
        <?php
        $this->form->prepare();
        echo $this->form()->openTag($form);
        ?>
        	<div class="card-header d-flex justify-content-between">
        		<div>
        			<b>Update</b>
        		</div>
        	</div>
        	
        	<div class="card-body">
        		<?php echo $this->formCollection($this->form); ?>
        	</div>
        <?php echo $this->form()->closeTag($this->form); ?>
        </div>  
    </div>
    <div class="col-md">
    	<div class="row mb-4">
    		<div class="col" style="max-height: 350px; overflow-y: auto;">
            	<?php echo $this->partial('midnet/subtable', [
            	    'title' => 'Classes',
            	    'data' => $this->classes,
            	    'primary_key' => 'UUID',
            	    'route' => 'training/default',
            	    'params' => [
            	        [
            	            'key' => 'UUID_C',
            	            'action' => 'update',
            	            'route' => 'training/default',
            	            'label' => 'Open',
            	        ],
            	    ],
            	])?>
    		</div>
    	</div>
    	<div class="row mb-4">
    		<div class="col" style="max-height: 350px; overflow-y: auto;">
            	<?php echo $this->partial('related_files', [
            	    'title' => 'Related Files',
            	    'data' => $this->files,
            	    'primary_key' => 'UUID',
            	    'route' => 'training/default',
            	    'params' => [
            	        [
            	            'key' => 'UUID',
            	            'action' => 'display',
            	            'route' => 'data',
            	            'label' => 'View',
            	        ],
            	    ],
            	])?>
    		</div>
    	</div>
    	<div class="row mb-4">
    		<div class="col" style="max-height: 350px; overflow-y: auto;">
            	<?php echo $this->partial('training/context_report', [
            	    'title' => 'Reports',
            	    'data' => $this->reports,
            	    'primary_key' => 'UUID',
            	    'route' => 'reports/default',
            	    'params' => [
            	        [
            	            'key' => 'UUID',
            	            'action' => 'view',
            	            'route' => 'reports/default',
            	            'label' => 'View',
            	            'num_vars' => 1,
            	            'vars' => [
            	                'FIELD0' => 'employees.UUID',
            	                'VALUE0' => $this->uuid,
            	            ],
            	        ],
            	    ],
            	])?>
    		</div>
    	</div>
    </div>
</div>