<div class="card-deck">
	<div class="card mb-4">
		<div class="card-header">
			<b>Find Class</b>
		</div>
		<div class="card-body">
			<?php 
			$form = $this->FindTrainingForm;
			$form->setAttribute('action', $this->url('training/default', ['action' => 'find']));
			$form->prepare();
			echo $this->form()->openTag($form);
			echo $this->formCollection($form);
			echo $this->form()->closeTag($form);
			?>
		</div>
	</div>
	<div class="card mb-4">
		<div class="card-header">
			<b>Find Employee</b>
		</div>
		<div class="card-body">
			<?php 
			$form = $this->FindEmployeeForm;
			$form->setAttribute('action', $this->url('employee/default', ['action' => 'find']));
			$form->prepare();
			echo $this->form()->openTag($form);
			echo $this->formCollection($form);
			echo $this->form()->closeTag($form);
			?>
		</div>
	</div>
</div>